name: Forward Telegram Messages

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:        # allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install telethon python-dotenv

      - name: Run script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SOURCE_CHANNEL: ${{ secrets.SOURCE_CHANNEL }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
        run: python main.py
