name: Forward Telegram Messages

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  forward-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install correct Telegram Bot library
        run: pip install python-telegram-bot==13.15

      - name: Run script
        run: python main.py
